---
title: "Slides"
engine: knitr 
---

* *[battery warning]{style="color:orange;"}*: several of the slide decks have running scripts (for the live polls), so saving the PDF copy and following it offline would use less of your battery.

# Class 1

```{r show-slide-tabs, echo=FALSE, results="asis"}
#| warning: false
slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_01")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_01.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
```

# Class 2

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-10-20")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_02")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_02.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

::: {.callout-important collapse="true"}
## Class 2 Lecture video - part 1

{{< video sm_class2_lecture_part1.mp4 >}}

:::

::: {.callout-important collapse="true"}
## Class 2 Lecture video - part 2

{{< video sm_class2_lecture_part2.mp4 >}}

:::


# Class 3

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-10-27")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_03")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_03.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```


# Class 4

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-11-03")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_04")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_04.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```


# Class 5

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-11-10")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_05")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_05.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

# Class 6 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-11-17")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_06")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_06.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```


# Class 7 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-11-24")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_07")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_07.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```



# Class 8 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-12-01")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_08")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_08.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

# Class 9 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-12-08")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_09")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_09.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

# Class 10 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2025-12-15")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_10")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_10.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

# Class 11 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2026-01-05")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_11")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_11.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

# Class 12 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2026-01-12")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_12")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_12.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```

# Class 13 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2026-01-19")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_13")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_13.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```


# Class 14 

```{r echo=FALSE, results="asis"}
#| warning: false
# if (Sys.Date() >= as.Date("2026-01-26")) {

slide_buttons <- function(slide_id) {
  glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>')
}

slide_buttons("/slides/slides_14")

library(xaringanExtra)

xaringanExtra::embed_xaringan(
  "/slides/slides_14.html",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
# }
```



<!-- # Class 2 -->

<!-- ```{r echo=FALSE, results="asis"} -->
<!-- #| warning: false -->
<!-- slide_buttons <- function(slide_id) { -->
<!--   glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>') -->
<!-- } -->

<!-- slide_buttons("/slides/slides_02") -->

<!-- library(xaringanExtra) -->

<!-- xaringanExtra::embed_xaringan( -->
<!--   "/slides/slides_02.html", -->
<!--   ratio = "16:9", -->
<!--   border = "none", -->
<!--   margin = "0 auto" -->
<!-- ) -->
<!-- ``` -->

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## Class 2 Lecture video - part 1 -->

<!-- {{< video fr_class2_lecture_part1.mp4 >}} -->

<!-- ::: -->

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## Class 2 Lecture video - part 2 -->

<!-- {{< video fr_class2_lecture_part2.mp4 >}} -->

<!-- ::: -->



<!-- ```{r echo=FALSE, results="asis"} -->
<!-- #| warning: false -->
<!-- if (Sys.Date() >= as.Date("2025-05-05")) { -->

<!-- slide_buttons <- function(slide_id) { -->
<!--   glue::glue('<p class="text-center buttons"><a class="btn btn-danger" target="_blank" href="{slide_id}.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> View all slides in new window</a> <a class="btn btn-danger" target="_blank" href="{slide_id}.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download PDF of all slides</a></p>') -->
<!-- } -->

<!-- slide_buttons("/slides/slides_03") -->

<!-- library(xaringanExtra) -->

<!-- xaringanExtra::embed_xaringan( -->
<!--   "/slides/slides_03.html", -->
<!--   ratio = "16:9", -->
<!--   border = "none", -->
<!--   margin = "0 auto" -->
<!-- ) -->
<!-- } -->
<!-- ``` -->





<!-- ## Class 1 -->

<!-- ```{css echo=FALSE} -->
<!-- .embed-container { -->
<!--     position: relative; -->
<!--     padding-bottom: 129%; -->
<!--     height: 0; -->
<!--     overflow: hidden; -->
<!--     max-width: 100%; -->
<!-- } -->

<!-- .embed-container iframe, -->
<!-- .embed-container object, -->
<!-- .embed-container embed { -->
<!--     position: absolute; -->
<!--     top: 0; -->
<!--     left: 0; -->
<!--     width: 100%; -->
<!--     height: 100%; -->
<!-- } -->
<!-- ``` -->

<!-- ```{=html} -->
<!-- <p class="text-center"> -->
<!--   <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$slides$pdf1`" target="_blank"> -->
<!--     <i class="bi-download"></i>&ensp;Download class slides -->
<!--   </a> -->
<!-- </p> -->

<!-- <div class="embed-container"> -->
<!--   <iframe src="`r rmarkdown::metadata$slides$pdf1`" style="border: 0.5px"></iframe> -->
<!-- </div> -->
<!-- ``` -->


<!-- # Class 2 -->

<!-- ```{css echo=FALSE} -->
<!-- .embed-container { -->
<!--     position: relative; -->
<!--     padding-bottom: 129%; -->
<!--     height: 0; -->
<!--     overflow: hidden; -->
<!--     max-width: 100%; -->
<!-- } -->

<!-- .embed-container iframe, -->
<!-- .embed-container object, -->
<!-- .embed-container embed { -->
<!--     position: absolute; -->
<!--     top: 0; -->
<!--     left: 0; -->
<!--     width: 100%; -->
<!--     height: 100%; -->
<!-- } -->
<!-- ``` -->

<!-- ```{=html} -->
<!-- <p class="text-center"> -->
<!--   <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$slides$pdf2`" target="_blank"> -->
<!--     <i class="bi-download"></i>&ensp;Download class slides -->
<!--   </a> -->
<!-- </p> -->

<!-- <div class="embed-container"> -->
<!--   <iframe src="`r rmarkdown::metadata$slides$pdf2`" style="border: 0.5px"></iframe> -->
<!-- </div> -->
<!-- ``` -->


